### ISSUE TITLE
Error w latest version

### ISSUE THREAD

**Issue by achterberg** [kw123/fingscan#1]
fingscan Error                  
Traceback (most recent call last):
  File "plugin.py", line 2738, in checkTriggers
    AwayTime[nDev] 	= timeNowm2-float(evnt["secondsOfLastOFF"][nDev])
KeyError: '12'
   fingscan Error                  
Traceback (most recent call last):
  File "plugin.py", line 2738, in checkTriggers
    AwayTime[nDev] 	= timeNowm2-float(evnt["secondsOfLastOFF"][nDev])
KeyError: '12'

**Comment by kw123** [comment]
Restart.  If still error: This means dev 12 does not exist. Please check the idevice variable and the fing devices KarlOn 15.12.2023, at 18:27, David Achterberg ***@***.***> wrote:﻿
fingscan Error
Traceback (most recent call last):
File "plugin.py", line 2738, in checkTriggers
AwayTime[nDev] 	= timeNowm2-float(evnt["secondsOfLastOFF"][nDev])
KeyError: '12'
fingscan Error
Traceback (most recent call last):
File "plugin.py", line 2738, in checkTriggers
AwayTime[nDev] 	= timeNowm2-float(evnt["secondsOfLastOFF"][nDev])
KeyError: '12'
